GestionStage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^entreprises/', include('entreprises.urls', namespace='entreprises')),
    url(r'^admin/', include(admin.site.urls)),
)

entreprises/urls.py
from django.conf.urls import patterns, url
from entreprises import views

urlpatterns = patterns("",
    url(r'^$', views.accueil, name='accueil'),
    url(r'^(?P<page>\d+)/?$', views.accueil, name='index-page'),
	url(r'^detailEntreprise/(?P<entreprise_id>\d+)/?$', views.detailEntreprise, name="detailEntreprise"),
	url(r'^delete/(?P<entreprise_id>\d+)/?$', views.delete, name="delete"),
    url(r'^ajouterEntreprise/$', views.ajouterEntreprise, name="ajouterEntreprise"),
    url(r'^modifierEntreprise/(?P<entreprise_id>\d+)/?$', views.modifierEntreprise, name="modifierEntreprise"),
    url(r'^detailEntreprise/(?P<entreprise_id>\d+)/?/maps$', views.geoloc, name="geolocal"),
)

entreprises/models.py
from django.db import models
from django.forms import ModelForm
import re


RE_CEDEX = re.compile(r'(.*)\b\s*cedex.*$',re.IGNORECASE|re.MULTILINE)
def addslashes(s):
    return re.sub("(\\\\|'|\")", lambda o: "\\"+o.group(1),s)

class Entreprise(models.Model,):
    nom        = models.CharField(max_length=100)
    adresse    = models.CharField(max_length=250)
    codePostal = models.CharField(max_length= 10)
    ville      = models.CharField(max_length= 50)
    pays       = models.CharField(max_length= 30)
    telephone  = models.CharField(max_length= 20)
    latitude   = models.FloatField()
    longitude  = models.FloatField()

    def __str__(self):
        return self.nom

    @property
    def latlng(self):
        return [self.latitude,self.longitude]

    @latlng.setter
    def latlng(self, x):
        self.latitude, self.longitude = x

    @property
    def ville_propre(self):
        v = self.ville
        m = RE_CEDEX.match(v)
        if m:
            v = m.group(1)
        return v
    @property
    def nom_propre(self):
        n =  self.nom
        return addslashes(n)

    
    @property
    def adresse_propre(self):
        a=self.adresse
        m =  RE_BP.match(a)
        if m:
            a= m.group(1)
        return addslashes(a)

class Contact(models.Model):
    entreprise = models.ForeignKey(Entreprise, related_name="contacts")
    nom        = models.CharField(max_length=30)
    libelle    = models.CharField(max_length=30)
    email      = models.EmailField(null=True, blank=True)
    telephone  = models.CharField(max_length=20)

    def __str__(self):
        return self.nom

class Pays(models.Model):
    code = models.PositiveSmallIntegerField(unique=True)
    alpha2 = models.CharField(max_length=2,unique=True)
    alpha3 = models.CharField(max_length=3,unique=True)
    nom_en_gb = models.CharField(max_length=45)
    nom_fr_fr = models.CharField(max_length=45)

    def __str__(self):
        return self.nom_fr_fr


class VillesDeFrance(models.Model):
    id                           = models.AutoField(primary_key=True, db_column="ville_id")
    departement                  = models.CharField(max_length=3,     db_column="ville_departement")
    slug                         = models.CharField(max_length=255,   db_column="ville_slug")
    nom                          = models.CharField(max_length=45,    db_column="ville_nom")
    nom_reel                     = models.CharField(max_length=45,    db_column="ville_nom_reel")
    nom_soundex                  = models.CharField(max_length=45,    db_column="ville_nom_soundex")
    nom_metaphone                = models.CharField(max_length=45,    db_column="ville_nom_metaphone")
    code_postal                  = models.CharField(max_length=255,   db_column="ville_code_postal")
    commune                      = models.CharField(max_length=3,     db_column="ville_commune")
    code_commune                 = models.CharField(max_length=5,     db_column="ville_code_commune")
    arrondissement               = models.PositiveSmallIntegerField(  db_column="ville_arrondissement")
    canton                       = models.CharField(max_length=4,     db_column="ville_canton")
    amdi                         = models.PositiveSmallIntegerField(  db_column="ville_amdi")
    population_2010              = models.PositiveIntegerField(       db_column="ville_population_2010")
    population_1999              = models.PositiveIntegerField(       db_column="ville_population_1999")
    population_2012              = models.PositiveIntegerField(       db_column="ville_population_2012")
    densite_2010                 = models.IntegerField(               db_column="ville_densite_2010")
    surface                      = models.PositiveIntegerField(       db_column="ville_surface")
    longitude_deg                = models.FloatField(                 db_column="ville_longitude_deg")
    latitude_deg                 = models.FloatField(                 db_column="ville_latitude_deg")
    longitude_grd                = models.CharField(max_length=9,     db_column="ville_longitude_grd")
    latitude_grd                 = models.CharField(max_length=8,     db_column="ville_latitude_grd")
    longitude_dms                = models.CharField(max_length=9,     db_column="ville_longitude_dms")
    latitude_dms                 = models.CharField(max_length=8,     db_column="ville_latitude_dms")
    zmin                         = models.IntegerField(               db_column="ville_zmin")
    zmax                         = models.IntegerField(               db_column="ville_zmax")
    population_2010_order_france = models.IntegerField(               db_column="ville_population_2010_order_france")
    densite_2010_order_france    = models.IntegerField(               db_column="ville_densite_2010_order_france")
    surface_order_france         = models.IntegerField(               db_column="ville_surface_order_france")

    class Meta:
        db_table = "villes_france"

    def __str__(self):
        return self.nom_reel
        
class AjoutForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(AjoutForm, self).__init__(*args, **kwargs)
		self.fields['nom'].label = "Nom "
		self.fields['adresse'].label = "Adresse"
		self.fields['codePostal'].label = "Code postal"
		self.fields['ville'].label = "Ville"
		self.fields['pays'].label = "Pays"
		self.fields['telephone'].label = "Telephone"
		self.fields['latitude'].label = "Latitude"
		self.fields['longitude'].label = "Longitude"

		#il est possible de metre que un seul champ en utilisant le model entreprise, il suffit de ne le préciser ni dans le init ni le meta
	class Meta:
		model = Entreprise
		fields = ('nom', 'adresse', 'codePostal','ville','pays' ,'telephone' ,'latitude' ,'longitude' )      
		
class ModifForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(ModifForm, self).__init__(*args, **kwargs)
		self.fields['nom'].label = "Nom"
		self.fields['adresse'].label = "Adresse"
		self.fields['codePostal'].label = "Code postal"
		self.fields['ville'].label = "Ville"
		self.fields['pays'].label = "Pays"
		self.fields['telephone'].label = "Telephone"
		self.fields['latitude'].label = "Latitude"
		self.fields['longitude'].label = "Longitude"
		
		#il est possible de metre que un seul champ en utilisant le model entreprise, il suffit de ne le préciser ni dans le init ni le meta
	class Meta:
		model = Entreprise
		fields = ('nom', 'adresse', 'codePostal','ville','pays' ,'telephone' ,'latitude' ,'longitude' )    		
        
class EntrepriseAjoutForm(ModelForm):
    class Meta:
        model = Entreprise

entreprises/templates/entreprises/ajouterEntreprise.html
{% extends 'commun.html' %}
{% block title %}{{ block.super }} - Ajouter une entreprise{% endblock %}

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Ajouter une entreprise</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <form class="form-horizontal" method="post" id="formEditionEntreprise">{% csrf_token %}
                    <fieldset>
                        <legend class="text-center header">Informations</legend>
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Nom</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="nom" name="nom" type="text" class="form-control center">
                            </div>
                        </div>
                        <div class="form-group">
                         <label class="col-md-3 col-md-offset-1">Adresse</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="adresse" name="adresse" type="text" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Code Postal</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="codePostal" name="codePostal" type="text" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Ville</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="ville" name="ville" type="text" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Pays</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="pays" name="pays" type="text" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Téléphone</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="telephone" name="telephone" type="text" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Latitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="latitude" name="latitude" type="text" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Longitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="longitude" name="longitude" type="text" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                            	<input class="btn btn-primary" type="submit" value="Envoyer" id="inputSubmit" />
                            	<button type="reset" class="btn btn-warning btn-large"><span class="glyphicon glyphicon-ban-circle"></span> Effacer</button>                 
                             </div>
                        </div>
                    </fieldset>
                </form>  
            </div>
        </div>
{% endblock %}
<!-- Block Corps - FIN -->

<!-- Block Maps - DEBUT -->
{% block maps %}{% include 'maps.html' %}{% endblock %}
<!-- Block Maps - FIN -->

entreprises/templates/entreprises/detailsEntreprises.html
{% extends 'commun.html' %}
{% block title %}{{ block.super }} - Détails de l'entreprise{% endblock %}

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Détails des données de l'entreprises</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <form class="form-horizontal" method="post" id="formEditionEntreprise">{% csrf_token %}
                    <fieldset>
                        <legend class="text-center header">Informations</legend>
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Nom</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="nom" name="nom" type="text" value="{{ detailEntreprise.nom }}" class="form-control center" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                         <label class="col-md-3 col-md-offset-1">Adresse</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="adresse" name="adresse" type="text" value="{{ detailEntreprise.adresse }}" class="form-control center" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Code Postal</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="codePostal" name="codePostal" type="text" value="{{ detailEntreprise.codePostal }}" class="form-control center" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Ville</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="ville" name="ville" type="text" value="{{ detailEntreprise.ville }}" class="form-control center" readonly>
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Pays</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="pays" name="pays" type="text" value="{{ detailEntreprise.pays }}" class="form-control center" readonly>
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Téléphone</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="telephone" name="telephone" type="text" value="{{ detailEntreprise.telephone }}" class="form-control center" readonly>
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Latitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="latitude" name="latitude" type="text" value="{{ detailEntreprise.latitude }}" class="form-control center" readonly>
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Longitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="longitude" name="longitude" type="text" value="{{ detailEntreprise.longitude }}" class="form-control center" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <a href="{% url 'entreprises:modifierEntreprise' entreprise_id=detailEntreprise.id %}" class="btn btn-warning btn-large">Editer</a>
                                <a href="{% url 'entreprises:delete' entreprise_id=detailEntreprise.id %}" class="btn btn-danger btn-large">Supprimer</a>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
{% endblock %}
<!-- Block Corps - FIN -->

<!-- Block Maps - DEBUT -->
{% block maps %}{% include 'maps.html' %}{% endblock %}
<!-- Block Maps - FIN -->

entreprises/templates/entreprises/erreur.html
{% extends 'commun.html' %}
{% block title %}{{ block.super }} | Entreprises{% endblock %}

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Gestion des données de l'entreprise</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="alert alert-danger" role="alert">
  	<span>{{ message }}</span>
  	<br> <br><span class="glyphicon glyphicon-arrow-left"></span> <a href="{% url 'entreprises:accueil'%}" class="alert-link">Retourner sur la liste des entreprises</a>
</div>
{% endblock %}
<!-- Block Corps - FIN -->

entreprises/templates/entreprises/index.html
{% extends 'commun.html' %} 
{% block title %}{{ block.super }} - Liste des entreprises{% endblock %} 

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Liste des entreprises</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                  <h3></h3>
                </div>
                <div class="panel-body">
                    <div class="sui-grid sui-grid-core" id="grid1">
                    	{% include 'pagination.html' %}
						<div class="sui-gridheader">
							<table class="sui-table sui-non-selectable">
								<thead>
									<tr class="sui-columnheader">
										<th class="sui-headercell center">Nom</th>
										<th class="sui-headercell center">Adresse</th>
										<th class="sui-headercell center cp">CP</th>
										<th class="sui-headercell center">Actions</th>
									</tr>
								</thead>
							</table>
						</div>
						<div class="sui-gridcontent">
							<table class="sui-table sui-hover sui-selectable">
								<tbody>
								{% for e in entreprises %}
								<!-- Changement couleur 1ligne/2 - DEBUT -->
									{% if forloop.counter0|divisibleby:2 %}
									<tr class="sui-alt-row">
									{% else %}
									<tr class="sui-row">
									{% endif %}
								<!-- Changement couleur 1ligne/2 - FIN -->
										<td class="sui-cell center">{{ e.nom }}</td>
										<td class="sui-cell center">{{ e.adresse }}</td>
										<td class="sui-cell center cp">{{ e.codePostal }}</td>
										<td class="sui-cell center">
											<a href="{% url 'entreprises:detailEntreprise' entreprise_id=e.id %}" class="btn btn-info">
												<span class="glyphicon glyphicon-file"></span> Détails
											</a>
											<a href="{% url 'entreprises:modifierEntreprise' entreprise_id=e.id %}" class="btn btn-warning">
												<span class="glyphicon glyphicon-pencil"> Editer</span>
											</a> 
											<a href="{% url 'entreprises:delete' entreprise_id=e.id %}" class="btn btn-danger">
												<span class="glyphicon glyphicon-remove"> Supprimer</span> 
											</a>
										</td>
									</tr>								
								{% endfor %}
								</tbody>
							</table>
						</div>
						{% include 'pagination.html' %}
					</div>
                
                </div>
            </div>
        </div>
    </div>
    <hr />
</div>
{% endblock %}
<!-- Block Corps - FIN -->

entreprises/templates/entreprises/modifierEntreprise.html
{% extends 'commun.html' %}
{% block title %}{{ block.super }} - Modifier une entreprise{% endblock %}

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Editer les données de l'entreprise</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <form class="form-horizontal" method="post" id="formEditionEntreprise">{% csrf_token %}
                    <fieldset>
                        <legend class="text-center header">Informations</legend>
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Nom</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="nom" name="nom" type="text" value="{{ detailEntreprise.nom }}" class="form-control center">
                            </div>
                        </div>
                        <div class="form-group">
                         <label class="col-md-3 col-md-offset-1">Adresse</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="adresse" name="adresse" type="text" value="{{ detailEntreprise.adresse }}" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Code Postal</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="codePostal" name="codePostal" type="text" value="{{ detailEntreprise.codePostal }}" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Ville</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="ville" name="ville" type="text" value="{{ detailEntreprise.ville }}" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Pays</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="pays" name="pays" type="text" value="{{ detailEntreprise.pays }}" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Téléphone</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="telephone" name="telephone" type="text" value="{{ detailEntreprise.telephone }}" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Latitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="latitude" name="latitude" type="text" value="{{ detailEntreprise.latitude }}" class="form-control center">
                            </div>
                        </div>
                        
                        <div class="form-group">
                        <label class="col-md-3 col-md-offset-1">Longitude</label>
                            <div class="col-md-10 col-md-offset-1">
                                <input id="longitude" name="longitude" type="text" value="{{ detailEntreprise.longitude }}" class="form-control center">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                            <input class="btn btn-primary" type="submit" value="Modifier" id="inputSubmit" />
                            	<!--  <button type="submit" href="#" class="btn btn-success btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Envoyer</button>-->
                           	 	<button type="reset" class="btn btn-warning btn-large"><span class="glyphicon glyphicon-ban-circle"></span> Effacer</button>                 
                             </div>
                        </div>
                    </fieldset>
                </form>  
            </div>
        </div>
      
{% endblock %}
<!-- Block Corps - FIN -->

<!-- Block Maps - DEBUT -->
{% block maps %}{% include 'maps.html' %}{% endblock %}
<!-- Block Maps - FIN -->

entreprises/templates/entreprises/success.html
{% extends 'commun.html' %}
{% block title %}{{ block.super }} | Entreprises{% endblock %}

<!-- Block Header - DEBUT -->
{% block header %}
<div class="page-header">
    <h1>Gestion des données de l'entreprise</h1>
</div>
{% endblock %}
<!-- Block Header - FIN -->

<!-- Block Corps - DEBUT -->
{% block corps %}
<div class="alert alert-success" role="alert">
  	<span>{{ message }}</span>
  	<br> <br><span class="glyphicon glyphicon-arrow-left"></span> <a href="{% url 'entreprises:accueil'%}" class="alert-link">Retourner sur la liste des entreprises</a>
</div>
{% endblock %}
<!-- Block Corps - FIN -->